- plugins/java
- plugins/maven
Though they are added in the README (commits 4d44d47 and 031dc6c6) the actual reference to repository is missing for commands `asdf plugin-add java` and `asdf plugin-add maven`.
> Add missing java and maven plugins to repository

- plugins/kops
kops (https://github.com/kubernetes/kops) helps you create, destroy, upgrade and maintain production-grade, highly available, Kubernetes clusters from the command line.
> Brand new kops plugin.

- plugins/solidity
I have implemented a Solidity plugin for the asdf version manager. It provides the basic `install` and `list-all` implementations. It supports Linux and macOS.
> Added Solidity asdf plugin

- README.md
- plugins/elasticsearch
Right now there is an out of date elasticsearch repo: https://github.com/lowski/asdf-elasticsearch
I have forked it and updated it to work with versions past 2.4.x: https://github.com/mikestephens/asdf-elasticsearch
i would love to get it in to the main repo list!
> Add elasticsearch repository

- plugins/coq
Add a Coq plugin git repo address: https://github.com/gingerhot/asdf-coq
> Add a Coq plugin repo

- README.md
- plugins/conduit
This pull request adds a plugin to manage versions of https://conduit.io/
> plugins: add conduit

- README.md
- plugins/cmake
This PR adds the asdf-cmake plugin, that builds and installs cmake from source.
> added cmake-plugin

- README.md
- plugins/clojure
Clojure build has changed dramatically since 1.9.0 release. The current clojure-asdf plugin does not work.
> Update Clojure plugin

- README.md
- plugins/heptio-authenticator-aws
Adding a plugin for [heptio-authenticator-aws](https://github.com/heptio/authenticator)
> Add heptio-authenticator-aws plugin

- README.md
- plugins/desk
Hello, I'd like to contribute the [`desk`](https://github.com/jamesob/desk) plugin I made.
Build status is [![Build Status](https://travis-ci.org/endorama/asdf-desk.svg?branch=master)](https://travis-ci.org/endorama/asdf-desk) :)
Thank you.
> add desk plugin

- README.md
- plugins/brig
Brig is a CLI tool for the [Azure/brigade](https://github.com/Azure/brigade) project.
Fixes https://github.com/Ibotta/asdf-brig/issues/5
> Add brig plugin

- README.md
- plugins/dep
The "dep" tool is widely used for Go dependency management:
- https://github.com/golang/dep
> Add plugin for golang dep tool.

- README.md
- plugins/python
https://github.com/tuvistavie/asdf-python -> https://github.com/danhper/asdf-python
analogous to https://github.com/danhper/asdf-python/pull/46
> fix travis for asdf-python with renamed repo

- plugins/java
The [skotchpine java plugin](https://github.com/skotchpine/asdf-java) has not been updated since late 2018. Since then several of the Oracle JDKs can no longer be installed as Oracle requires a login for anything higher than oracle-8.141. I've incorporated changes from the openjdk/zulu related PRs that have been awaiting attention for months in the skotchpine java repo. I've removed the Oracle JDKs that can no longer be installed and replaced/augmented them with [Azul's Zulu builds](https://www.azul.com/downloads/zulu/). If @skotchpine would prefer me create a PR for their plugin, I would be glad to do so - but in light of their current backlog of PRs, it appears that they might prefer to pass the torch to a new maintainer.
> Update java plugin

- README.md
- plugins/yarn
This PR introduces an asdf plugin for [Yarn](https://yarnpkg.com/en/), a popular alternative to NPM for JavaScript libraries and applications. This plugin has been a missing piece for me for some time now, so I figured it's long overdue to join the asdf plugin ecosystem.
Source: https://github.com/twuni/asdf-yarn
> ✨ Add plugin for Yarn

- README.md
- plugins/eksctl
Adds a plugin to manage the Weaveworks EKS tool `eksctl`.
https://github.com/weaveworks/eksctl
> Add eksctl plugin

- test.sh
* Add ability to skip tests for travis-ci.com (enterprise).
* Print a summary upon completion showing numbers of plugins,
number skipped, and number failed.
Helps with #84 and #85.
After poking around a bit I see that all of the Travis Enterprise checks are detected as failing. Also, some of the checks in this script were failing while the real build was successful because the success/fail check was only looking at the most recent build instead of the build on the target branch.
test.sh now _skips_ enterprise links and should detect the rest of the success/fail correctly.
Script output looks like the following now:
```
Plugin build check failed:  https://travis-ci.org/marciogm/asdf-crystal
Plugin build check failed:  https://travis-ci.org/mikestephens/asdf-elasticsearch
Plugin build check …
```
> Enhance test.sh to better detect success/fail.

- README.md
- plugins/bazel
The `list-all` in the currently included repository is invalid as it lists hard coded versions vs all released versions.
Have opened a PR with the upstream as well https://github.com/mrinalwadhwa/asdf-bazel/pull/3
> Use a different Bazel plugin

- README.md
- plugins/v
`asdf-v` uses symlinks to enable asdf versioning.
Currently the path is hardcode-limited to `~/code/v`, so `asdf-v` deletes and create the symlink there. If the user has a predefined `~/code/v`, it may be an issue.
This limitation is planned to be gone, when V enables flexible installation paths.
> add V (The V Programming Language) plugin

- README.md
- plugins/chicken
Hi there, here's a plugin for [CHICKEN](https://wiki.call-cc.org/).
There's no support for macOS (yet), so the Travis build only runs on Linux.
> Add CHICKEN plugin

- README.md
- plugins/maven
The [skotchphine maven plugin](https://github.com/asdf-vm/asdf-plugins/pull/78) has not been updated since July 2018 and has been broken for some time.
> Fix broken maven plugin

- test_plugin.sh
As cited in #428, I misinterpreted the output of `test_plugin.sh` partly because the output looked like pretty standard output. This change adds "FAIL:" to any output that is considered a failure to make the failures more apparent. 
Thank you for contributing to asdf-plugins!
> fix: prepend FAIL to any failures in test_plugin.sh

- .github/workflows/workflow.yml
- README.md
- plugins/1password-cli
- remove refs to Travis CI script no longer in use noted in #84
- cleans up the documentation to simplify and make it much more clear that `asdf plugin add <name> <git_url>` is an option.
- ~update CI to use `${{ github.base_ref }}` instead of harcoded `origin/master`~
> docs: clean up Travis refs

- README.md
- link `asdf-community` closing #180 
- add a Security section describing responsibility of users to eval plugins themselves and how to pin to a specific `sha` of a plugin.
```bash
```
> docs: security notice & link asdf-community

- plugins/R
I forgot to update this file since the repo migrated to the community.
Probably Github keeps the "redirect" from the repo but it would be good to have this reference updated to the current repository.
```bash
```
> chore: update asdf-r repo

- .github/workflows/format.yml
- .github/workflows/test.yml
Auto-format `README.md` on merges to main where the `README.md` has changed. Removes `prettier --check` from CI on PRs.
I am very tired of having to correct formatting issues to match `prettier` which no one runs before committing.
> ci: format readme when updated on main

- README.md
Just a link update.
```bash
```
> Update link to plugin doc

- .github/dependabot.yml
This will use dependabot to check any github action this project uses for updates in order to keep it up-to-date.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
```bash
```
> ci: dependabot for github actions

- SECURITY.md
Explicitly state that asdf does not provide security policy for the plugins listed in this repo.
> docs: explicitly state no security for this repo

- CONTRIBUTING.md
This is not a tool or plugin update, but a minor "fix" regarding what I pointed out [here](https://github.com/asdf-vm/asdf-plugins/pull/847#issuecomment-1607984491).
> docs: tell contributors about Conventional Commits in docs

- .github/workflows/semantic-pr.yml
As with https://github.com/asdf-vm/asdf/pull/1642
GitHub now supports, and we use, the setting which sets the squash commit message the PR title.
Since this is now the case, we no longer require single-commit-PRs to have those single commits match the Semantic PR settings.
This will mean the errors from Semantic PR only apply to PR titles and are therefore easier to fix than the single-commit commit message.
I noticed this **unnecessarily** tripping some people up across the repos. Eg: https://github.com/asdf-vm/asdf-plugins/pull/882
> ci: remove semantic release single-commit rule

- scripts/test_plugin.bash
See #943.
This PR removes the check for the CI badges from the `scripts/test_plugin.bash` script, because they have been removed.
> fix: do not check CI badges

- README.md
- plugins/ksops
Description:
- Tool repo URL: https://github.com/viaduct-ai/kustomize-sops
- Plugin repo URL: https://github.com/janpieper/asdf-ksops
> feat: add ksops plugin

- README.md
- plugins/regal
Description:
- Tool repo URL: https://github.com/StyraInc/regal
- Plugin repo URL: https://github.com/asdf-community/asdf-regal
> feat: add regal plugins

- plugins/luajit
In the same style as 23196487296ba3dea97bf6cc10bf5071081baa21, add entry with lowercase. This is the only other instance of such a case.
- Tool repo URL: N/A
- Plugin repo URL: N/A
> fix: Add luaJIT with lowercase name

- README.md
- plugins/shorebird
Description:
- Tool repo URL: https://docs.shorebird.dev/overview
- Plugin repo URL: https://github.com/valian-ca/asdf-shorebird
> feat: add shorebird plugin

- README.md
- plugins/libsql-server
Description:
- Tool repo URL: https://github.com/tursodatabase/libsql/tree/main/libsql-server
- Plugin repo URL: https://github.com/jonasb/asdf-libsql-server
> feat: add libsql-server plugin

- README.md
- plugins/calendarsync
Description:
- Tool repo URL: https://github.com/inovex/CalendarSync
- Plugin repo URL: https://github.com/FeryET/asdf-calendarsync
> feat: adds CalendarSync asdf-plugin

- README.md
- plugins/k3s
Add new plugin for k3s binary.
Description:
- Tool repo URL: https://github.com/k3s-io/k3s
- Plugin repo URL: https://github.com/dmpe/asdf-k3s
- only for linux, mac14 github action runner did not worked (the project does not seem to support mac m1+)
> feat: add new k3s plugin

- README.md
- plugins/hishtory
Description:
- Tool repo URL: https://github.com/ddworken/hishtory
- Plugin repo URL: https://github.com/asdf-community/asdf-hishtory
> feat: add hishtory plugins

- README.md
- plugins/cljstyle
Description: cljstyle plugin, a tool for formatting Clojure code
- Tool repo URL: https://github.com/greglook/cljstyle
- Plugin repo URL: https://github.com/abogoyavlensky/asdf-cljstyle
> feat: add cljstyle plugin

- README.md
- plugins/bazelisk
Description: Add bazelisk plugin. Bazelisk is a version manager for the bazel build tool.
- Tool repo URL: https://github.com/bazelbuild/bazelisk
- Plugin repo URL: https://github.com/josephtate/asdf-bazelisk
- [X ] Format with `scripts/format.bash`
- [X ] Test locally with `scripts/test_plugin.bash --file plugins/<your_new_plugin_name>`
- [X ] Your plugin CI tests are green
> feat: Add bazelisk plugin

- README.md
- plugins/ruff
Description:
- Tool repo URL: https://github.com/asdf-vm/asdf
- Plugin repo URL: https://github.com/simhem/asdf-ruff
> feat: Add ruff plugin

- README.md
- plugins/hub
Description:
The version I point to is updated with more version work and it's using the more used $GITHUB_API_TOKEN variable
> fix: use updated plugin hub version

- README.md
- plugins/liquibase
Description:
- Tool repo URL: https://github.com/liquibase/liquibase
- Plugin repo URL: https://github.com/saliougaye/asdf-liquibase
> feat: add liquibase plugin

- README.md
- plugins/yamlscript
- Tool repo URL: https://github.com/yaml/yamlscript
- Plugin repo URL: https://github.com/FeryET/asdf-yamlscript/
> feat: adds yamlscript plugin

- README.md
- plugins/k3kcli
Description:
- Tool repo URL: https://github.com/rancher/k3k
- Plugin repo URL: https://github.com/xanmanning/asdf-k3kcli
> feat: add k3kcli plugin repo

- README.md
- plugins/kpack
Description:
- Tool repo URL: https://github.com/buildpacks-community/kpack
- Plugin repo URL: https://github.com/asdf-community/asdf-kpack-cli
> feat: add kpack

- README.md
- plugins/jnv
Description:
- Tool repo URL:https://github.com/ynqa/jnv
- Plugin repo URL:https://github.com/raimon49/asdf-jnv
This is the result of a test run.
```bash
$ scripts/test_plugin.bash --file plugins/jnv
OK plugins/jnv
```
> feat: add jnv plugin

- README.md
- plugins/git-cliff
Description:
- Tool repo URL: https://github.com/orhun/git-cliff
- Plugin repo URL: https://github.com/jylenhof/asdf-git-cliff
> feat: add git-cliff asdf plugin

- README.md
- plugins/apollo-ios-cli
Description:
- Tool repo URL: https://github.com/apollographql/apollo-ios-codegen, but binaries distributed in https://github.com/apollographql/apollo-ios
- Plugin repo URL: https://github.com/MacPaw/asdf-apollo-ios-cli
> feat: add apollo-ios-cli

- README.md
- plugins/sentry-cli
Description:
- Tool repo URL: https://github.com/getsentry/sentry-cli
- Plugin repo URL: https://github.com/MacPaw/asdf-sentry-cli
> feat: add sentry-cli

- README.md
- plugins/xcbeautify
Description:
- Tool repo URL: https://github.com/cpisciotta/xcbeautify
- Plugin repo URL: https://github.com/MacPaw/asdf-xcbeautify
> feat: add xcbeautify

- README.md
- plugins/bin
Description:
- Tool repo URL:
- Plugin repo URL:
> fix: remove Bin plugin that no longer exists

- README.md
- plugins/tfcmt
Description:
- Tool repo URL: https://github.com/suzuki-shunsuke/tfcmt
- Plugin repo URL: https://github.com/nasa9084/asdf-tfcmt
> feat: add tfcmt plugin

- README.md
- plugins/sync
Description: `asdf sync` is a plugin which implements an asdf extension command to synchronize plugins. It also offers the ability to use Semantic Versioning based version constraints using common constraint syntax, and to specify a plugin URL and/or ref in the comments of .tool-versions.
- Tool repo URL: https://github.com/robzr/asdf-sync
- Plugin repo URL: https://github.com/robzr/asdf-sync
> feat: add asdf sync plugin

- README.md
- plugins/xcresultparser
Description:
- Tool repo URL: https://github.com/a7ex/xcresultparser
- Plugin repo URL: https://github.com/MacPaw/asdf-xcresultparser
> feat: add xcresultparser

- README.md
- plugins/garden-cli
Description:
- Tool repo URL: https://github.com/nextjournal/garden-cli
- Plugin repo URL: https://github.com/rynkowsg/asdf-garden-cli
> feat: add garden-cli plugin

- README.md
- plugins/auth0-cli
Description:
- Tool repo URL: https://github.com/auth0/auth0-cli
- Plugin repo URL: https://github.com/gunzy83/asdf-auth0-cli
> feat: add auth0-cli plugin

- README.md
- plugins/pandoc-crossref
Description:
- Tool repo URL: https://github.com/lierdakil/pandoc-crossref
- Plugin repo URL: https://github.com/sys9kdr/asdf-pandoc-crossref
> feat: add pandoc-crossref plugin

- README.md
- plugins/launchpad
Description:
- Tool repo URL: https://github.com/Mirantis/launchpad
- Plugin repo URL: https://github.com/surskitt/asdf-launchpad
> feat: add mirantis launchpad plugin

- README.md
- plugins/cargo-make
- plugins/yamlfmt
- plugins/zigmod
Description:
https://github.com/orgs/mise-plugins/discussions/13
I have transferred repository owner of my plugins for a community.
> fix: update plugins owner for cargo-make, yamlfmt and zigmod

- README.md
- plugins/jetbrains
ASDF plugin for JetBrains tools:
- clion      - CLion
- datagrip   - DataGrip
- dataspell  - DataSpell
- gateway    - Gateway
- goland     - GoLand
- idea       - IntelliJ IDEA Ultimate
- ideac      - IntelliJ IDEA Community Edition
- mps        - MPS
- phpstorm   - PhpStorm
- pycharm    - PyCharm Professional Edition
- pycharmc   - PyCharm Community Edition
- rider      - Rider
- rideru     - Rider for Unreal Engine
- rubymine   - RubyMine
- webstorm   - WebStorm
- JetBrains products: https://www.jetbrains.com/products/
- Plugin repo URL: https://github.com/asdf-community/asdf-jetbrains
> feat: asdf-jetbrains plugin

- README.md
- plugins/dojo
Description:
- Tool repo URL: https://github.com/dojoengine/dojo
- Plugin repo URL: https://github.com/dojoengine/asdf-dojo/
> feat: add dojo plugin

- README.md
- plugins/e1s
Description:
- Tool repo URL: https://github.com/keidarcy/e1s
- Plugin repo URL: https://github.com/tbobm/asdf-e1s
> feat: add asdf-e1s plugin

- README.md
- plugins/spark
Description:
- Tool repo URL: https://github.com/sudo-black/asdf-spark.git
- Plugin repo URL: https://github.com/sudo-black/asdf-spark.git
> fix: change spark plugin to fixed fork

- README.md
- plugins/doctl
Description:
- Tool repo URL: https://github.com/digitalocean/doctl/
- Plugin repo URL: https://github.com/bstoutenburgh/asdf-doctl
This is an older plugin. I had changed my github username, this updates the reference before redirects stop working.
```shell
$ curl -s -w '%{http_code} - %{redirect_url}\n' "https://github.com/maristgeek/asdf-doctl/"
301 - https://github.com/bstoutenburgh/asdf-doctl
```
> chore: update doctl plugin reference

- README.md
- plugins/aapt2
Add [AAPT2 (Android Asset Packaging Tool)](https://developer.android.com/tools/aapt2) plugin.
Description:
- Tool repo URL: https://maven.google.com/web/index.html#com.android.tools.build:aapt2
- Plugin repo URL: https://github.com/ronnnnn/asdf-aapt2
> feat: AAPT2 plugin

- README.md
- plugins/versio
Description:
- Tool repo URL: https://github.com/chaaz/versio
- Plugin repo URL: https://github.com/pdemagny/asdf-versio
(The CI on the plugin is not green for MacOS because of missing openssl lib on the runner, but the asdf plugin itself downloads the binary as it should).
> feat: add versio

- README.md
- plugins/starkli
Description: CLI tool for Starknet
- Tool repo URL: https://github.com/xJonathanLEI/starkli
- Plugin repo URL: https://github.com/ptisserand/asdf-starkli
> feat: add starkli plugin

- README.md
- plugins/starknet-devnet
Description: A local testnet for Starknet... in Rust
- Tool repo URL: https://github.com/0xSpaceShard/starknet-devnet-rs
- Plugin repo URL: https://github.com/ptisserand/asdf-starknet-devnet
> feat: add starknet-devnet plugin

- README.md
- plugins/pixi
Description:
- Tool repo URL: https://github.com/prefix-dev/pixi
- Plugin repo URL: https://github.com/pavelzw/asdf-pixi
> feat: Add asdf-pixi

- README.md
- plugins/tekton-pac-cli
Description:
- Tool repo URL:  https://github.com/openshift-pipelines/pipelines-as-code
- Plugin repo URL: https://github.com/ifireball/asdf-tekton-pac-cli.git
> feat: add the tekton-pac-cli plugin

- README.md
- plugins/tf
Less verbose and more shell friendly Terraform wrapper
Description:
- Tool repo URL: https://github.com/dex4er/tf
- Plugin repo URL: https://github.com/dex4er/asdf-tf
> feat: add tf plugin

- README.md
- plugins/jet
Description:
- Tool repo URL: https://github.com/borkdude/jet
- Plugin repo URL: https://github.com/rynkowsg/asdf-jet
> feat: Add jet

- README.md
- plugins/kubeone
Description:
- Tool repo URL: https://github.com/kubermatic/kubeone
- Plugin repo URL: https://github.com/PandaScience/asdf-kubeone
> feat: add kubeone plugin

- README.md
- plugins/phrase
Phrase App Cli asdf plugin.  Fork of 'official one' that no longer responds to github issues.
Description:
- Tool repo URL: https://github.com/phrase/phrase-cli
- Plugin repo URL: https://github.com/bitfrost/asdf-phrase
> feat: add phrase app cli plugin

- README.md
- plugins/sst
Description:
- Tool repo URL: https://github.com/sst/ion
- Plugin repo URL: https://github.com/nurulhudaapon/asdf-sst
> feat: add sst plugin

- README.md
- plugins/mdbook
The current `mdbook` plugin is based on [an archived repository](https://github.com/cipherstash-archive/asdf-mdbook). There are a couple of issues with its implementation that people have already reported and created PRs for, but the maintainer of that project hasn't responded for over a year. I forked that project and fixed those issues. This PR replaces the current mdbook plugin with my fork.
Description:
- Tool repo URL: https://github.com/rust-lang/mdBook
- Plugin repo URL: https://github.com/hashemi-soroush/asdf-plugins/
> feat: change mdbook plugin repo

- README.md
- plugins/argocd-image-updater
Description:
- Tool repo URL: https://argocd-image-updater.readthedocs.io/en/stable/
- Plugin repo URL: https://github.com/thatmlopsguy/asdf-argocd-image-updater
> feat: add argocd-image-updater plugin

- README.md
- plugins/eks-node-viewer
Description:
- Tool repo URL:
- Plugin repo URL: https://github.com/haad/asdf-eks-node-viewer
> feat: Add eks-node-viewer plugin

- README.md
- plugins/gobackup
Description:
- Tool repo URL: https://github.com/gobackup/gobackup
- Plugin repo URL: https://github.com/0ghny/asdf-gobackup
> feat: add gobackup plugin

- README.md
- plugins/restish
Description: Add `restish` plugin. 
> [Restish](https://rest.sh/) is a CLI for interacting with [REST](https://apisyouwonthate.com/blog/rest-and-hypermedia-in-2019)-ish HTTP APIs with some nice features built-in, like always having the latest API resources, fields, and operations available when they go live on the API without needing to install or update anything.
- Tool repo URL:  https://github.com/danielgtaylor/restish
- Plugin repo URL: https://github.com/polds/asdf-restish
> feat: add restish plugin

- README.md
- plugins/exercism
Description:
- Tool repo URL: https://github.com/exercism/cli
- Plugin repo URL: https://gitlab.com/bheesham/asdf-exercism
> feat: add exercism plugin

- README.md
- plugins/fluttergen
Add [FlutterGen](https://github.com/FlutterGen/flutter_gen) plugin.
Description:
- Tool repo URL: https://github.com/FlutterGen/flutter_gen
- Plugin repo URL: https://github.com/FlutterGen/asdf-fluttergen
> feat: FlutterGen plugin

- README.md
- plugins/scaffold
Description: Add the [scaffold](https://github.com/hay-kot/scaffold) plugin.
- Tool repo URL: [https://github.com/hay-kot/scaffold](https://github.com/hay-kot/scaffold)
- Plugin repo URL: [https://github.com/particledecay/asdf-scaffold](https://github.com/particledecay/asdf-scaffold)
> feat: add scaffold from hay-kot/scaffold

- README.md
- plugins/micronaut
Description:
- Tool repo URL: [Micronaut](https://micronaut.io/)
- Plugin repo URL: https://github.com/xafarr/asdf-micronaut
> fix: replace the asdf-micronaut plugin

- README.md
- plugins/spotbugs
Description: Add `asdf-spotbugs` plugin for `spotbugs`.
- Tool repo URL: https://github.com/spotbugs/spotbugs
- Plugin repo URL: https://github.com/jiahuili430/asdf-spotbugs
```bash
$ scripts/test_plugin.bash --file plugins/spotbugs
OK plugins/spotbugs
```
> feat: add spotbugs plugin

- README.md
- plugins/c3
Description:
- Tool repo URL: https://github.com/c3lang/c3c
- Plugin repo URL: https://github.com/robloach/asdf-c3/
> feat: add C3 plugin

- README.md
- plugins/resticprofile
Description:
- Tool repo URL: https://github.com/creativeprojects/resticprofile
- Plugin repo URL: https://github.com/olofvndrhr/asdf-resticprofile
> feat: add plugin resticprofile

- README.md
- plugins/kubectl-buildkit
Remove the kubectl-buildkit plugin added in #672.
[kubectl-buildkit](https://github.com/vmware-archive/buildkit-cli-for-kubectl) has been deprecated and moved to the Vmware archive.
ezCater has archived their asdf plugin for the same as a result: https://github.com/ezcater/asdf-kubectl-buildkit/pull/2
> chore: remove kubectl-buildkit plugin

- README.md
- plugins/dotenvx
Description:
- Tool repo URL: https://github.com/dotenvx/dotenvx
- Plugin repo URL: https://github.com/jgburet/asdf-dotenvx
> feat: add dotenvx plugin

- README.md
- plugins/esc
Description:
- Tool repo URL: https://github.com/pulumi/esc
- Plugin repo URL: https://github.com/fxsalazar/asdf-esc
> feat: Add (pulumi) esc plugin 

- README.md
- plugins/avalanche
Description:  Adding the avalanche CLI
- Tool repo URL: https://github.com/ava-labs/avalanche-cli
- Plugin repo URL: https://github.com/embtools/asdf-avalanche
> feat: adding avalanche-cli

- README.md
- plugins/spark
The other spark plugin repo is broken
Description:
Updated the spark plugin repo to a working one.
> Ran `scripts/format.bash` and it didn't report any changes. So I don't know why CI is failing...
- Tool repo URL:
- Plugin repo URL:
> fix: update spark plugin

- README.md
- plugins/devpod-cli
Description:
- Tool repo URL: https://github.com/loft-sh/devpod
- Plugin repo URL: https://github.com/salemgolemugoo/asdf-devpod-cli
> feat: add devpod-cli

- README.md
- plugins/stratus-red-team
Description:
- Tool repo URL: https://github.com/DataDog/stratus-red-team
- Plugin repo URL: https://github.com/vthiery/asdf-stratus-red-team
> feat: add stratus-red-team plugin

- README.md
- plugins/planetscale-cli
Description:
- Tool repo URL: https://planetscale.com/docs/reference/planetscale-cli
- Plugin repo URL: https://github.com/kota65535/asdf-planetscale-cli.git
> feat: add PlanetScale CLI

- README.md
- plugins/process-compose
Description:
- Tool repo URL: https://github.com/F1bonacc1/process-compose
- Plugin repo URL: https://github.com/martino/asdf-process-compose
> feat:  add process-compose

- README.md
- plugins/avalanchego
Adding plugin for avalanchego, an Avalanche node server
*This differs from the avalanche plugin which is the developer tool, not the server itself*
Description:
- Tool repo URL: https://github.com/ava-labs/avalanchego
- Plugin repo URL: https://github.com/embtools/asdf-avalanchego
> feat: adding plugin for avalanchego

- README.md
- plugins/rustic
Description:
- Tool repo URL: https://github.com/rustic-rs/rustic
- Plugin repo URL: https://github.com/jahands/asdf-rustic
- https://github.com/jahands/asdf-rustic/actions/runs/11326518078
> feat: Add rustic backup plugin

- README.md
- plugins/argc
Description:
- Tool repo URL: https://github.com/sigoden/argc
- Plugin repo URL: https://github.com/rgeraskin/asdf-argc
> feat: add argc plugin

- README.md
- plugins/supabase-cli
Description:
- Tool repo URL: https://github.com/supabase/cli
- Plugin repo URL: https://github.com/gavinying/asdf-supabase-cli
> feat: Add Supabase CLI plugin

- README.md
- plugins/atmos
Description:
- Tool repo URL: https://github.com/cloudposse/atmos
- Plugin repo URL: https://github.com/cloudposse/asdf-atmos
> feat: Add Atmos by Cloud Posse

- README.md
- plugins/hcp
Description:
Adds `hcp` via the asdf-hashicorp plugin.
- Tool repo URL: https://github.com/hashicorp/hcp
- Plugin repo URL: https://github.com/asdf-community/asdf-hashicorp
> feat: add hcp

- README.md
- plugins/kubectl-oidc_login
Adds the `kubectl-oidc_login` plugin to the repository.
Note: the tool being installed calls itself `kubelogin` but, due to the name being overloaded (e.g. another plugin in this repo), it is installed as `kubectl-oidc_login` ([reference](https://github.com/int128/kubelogin?tab=readme-ov-file#setup)). This is why this name was chosen for the plugin.
Description:
- Tool repo URL: [int128/kubelogin](https://github.com/int128/kubelogin)
- Plugin repo URL: [ezcater/asdf-kubectl-oidc_login](https://github.com/ezcater/asdf-kubectl-oidc_login)
Note: this is a recreation of #1067 which was closed because we accidentally cleaned up our fork of this repo.
> feat: add kubectl-oidc_login plugin

- README.md
- plugins/lq
Description:
- Tool repo URL: https://github.com/clux/lq
- Plugin repo URL: https://github.com/jylenhof/asdf-lq
> feat: add lq asdf plugin

- README.md
- plugins/terragrunt
We recently adopted the asdf plugin for Terragrunt:
https://github.com/ohmer/asdf-terragrunt/issues/3#issuecomment-2537238311
Do you mind updating the registry to reflect that?
> feat: Migrating Terragrunt asdf plugin over to gruntwork-io

- README.md
- plugins/cairo-profiler
Description:
- Tool repo URL: https://github.com/software-mansion/cairo-profiler
- Plugin repo URL: https://github.com/software-mansion/asdf-cairo-profiler
> feat: add cairo-profiler

- README.md
- plugins/ghostty
Description:
- Tool repo URL: https://github.com/ghostty-org/ghostty/
- Plugin repo URL: https://github.com/ilvez/asdf-ghostty/
> feat: Add ghostty

- README.md
- plugins/cairo-coverage
Description:
- Tool repo URL: https://github.com/software-mansion/cairo-coverage
- Plugin repo URL: https://github.com/software-mansion/asdf-cairo-coverage
> feat: add cairo-coverage

- README.md
- plugins/signal-cli
Description:
- Tool repo URL: https://github.com/AsamK/signal-cli
- Plugin repo URL: https://github.com/ehsash/asdf-signal-cli
> feat: Add signal-cli to plugins list

- README.md
- plugins/alire
Description:
- Tool repo URL: https://github.com/alire-project/alire
- Plugin repo URL: https://github.com/NyanHelsing/asdf-alire
> feat: Adds plugin for alire

- README.md
- plugins/boilerplate
Description:
- Tool repo URL: https://github.com/gruntwork-io/boilerplate
- Plugin repo URL: https://github.com/gruntwork-io/asdf-boilerplate
> feat: add gruntwork boilerplate

- README.md
- plugins/calicoctl
Description: Replace the currently provided `calicoctl` plugin with the upstream repository it was forked from. The currently used repository does not currently work, but the upstream repository works as expected.
- Tool repo URL: https://github.com/projectcalico/calico/
- Plugin repo URL: https://github.com/teejaded/asdf-calicoctl
> fix: replace calicoctl plugin with its upstream

- README.md
- plugins/bat
- plugins/tmux
A terminal multiplexer: it enables a number of terminals to be created, accessed, and controlled from a single screen.
- Tool repo URL: https://github.com/tmux/tmux
- Plugin repo URL: https://github.com/pauloedurezende/asdf-tmux
A cat(1) clone with syntax highlighting and Git integration.
- Tool repo URL: https://github.com/sharkdp/bat
- Plugin repo URL: https://github.com/pauloedurezende/asdf-bat
This pull request proposes changing the existing plugin links for `tmux` and `bat` in the `asdf-plugins` repository. These changes are necessary due to issues identified with the current installations of the plugins:
1. **`bat` Plugin:**
- The `bat` plugin is unable to install correctly because it cannot find the correct download URL. This issue prevents users from installing and using `bat` …
> feat: update repository URLs for bat and tmux plugins

- README.md
- plugins/ffizer
Description:
- Tool repo URL: https://github.com/ffizer/ffizer
- Plugin repo URL: https://github.com/ffizer/asdf-ffizer
> feat: Add ffizer plugin

- README.md
- plugins/yasm
Description:
- Tool repo URL: https://github.com/yasm/yasm
- Plugin repo URL: https://github.com/kkHAIKE/asdf-plugins
> feat: Add Yasm plugin
