asdf-vm/asdf-plugins

- README.md
- plugins/vault
> Add HashiCorp's Vault

- README.md
- plugins/kubectl
> adding kubectl

- README.md
- plugins/kubecfg
https://github.com/ksonnet/kubecfg
> Add kubecfg

- README.md
- plugins/bazel
a plugin for bazel https://bazel.build/
> add bazel plugin

- README.md
- plugins/helm
Plugin that installs [Helm](https://github.com/kubernetes/helm)
> Brand new Helm plugin.

- README.md
- plugins/dotnet-core
Adding suport for [.Net Core](https://github.com/dotnet/core)
> .Net Core Plugin

- README.md
- plugins/swiprolog
> Add of SWI-Prolog plugin to list

- README.md
- plugins/docker-slim
https://github.com/everpeace/asdf-docker-slim
> add docker-slim plugin

- README.md
- plugins/protoc
Protobuf is a widely-used data interchange format:
- https://github.com/protocolbuffers/protobuf
> Add plugin for protobuf compiler protoc.

- README.md
- plugins/io
Add of plugin for the io language
The build is failing on MacOS but i really don't know what is :(
And as i don't have a mac, i don't know how to debug it
> add of io repository

- README.md
- plugins/dart
Hi, I'd like to add my Dart plugin if that's cool.
> Add Dart plugin

- README.md
While working on another PR (coming!) I noticed few problems in the README, so here's the fix for:
* broken link to plugin creation guide
* bitbucket pipeline badge for GoHugo plugin
Thanks for this super handy tool!
> fix: improvements in README

- README.md
- plugins/rancher
This MR adds a new rancher plugin to the asdf plugin list
> add rancher plugin

- README.md
- plugins/doctl
Not a language but I find this is helpful for me on Linux systems since DigitalOcean isn't currently pushing snaps.
> add doctl plugin

- README.md
- plugins/cf
For https://github.com/cloudfoundry/cli
> Add cf plugin

- README.md
- plugins/fluxctl
Adding plugin for fluxctl the CLI tool for Weave Flux https://github.com/weaveworks/flux
> Adding fluxctl plugin

- README.md
- plugins/kubeseal
Adding plugin for kubeseal the CLI tool for Sealed Secrets https://github.com/bitnami-labs/sealed-secrets
> Adding kubeseal plugin

- README.md
- plugins/riff
Add plugin for Riff (https://projectriff.io/)
> add riff plugin

- README.md
- plugins/istioctl
Add Istio (https://istio.io) CLI plugin: https://github.com/rafik8/asdf-istioctl
> Add istioctl plugin

- README.md
- plugins/micronaut
> Add plugin Micronaut

- README.md
- plugins/hub
asdf plugin for the [GitHub hub CLI](https://hub.github.com).
> Add vixus0/asdf-hub

- README.md
- plugins/kubecfg
> Delete kubecfg plugin since it is undocumented

- README.md
- plugins/conftest
| conftest | [looztra/asdf-conftest](https://github.com/looztra/asdf-conftest) | [![Build Status](https://travis-ci.org/looztra/asdf-conftest.svg?branch=master)](https://travis-ci.org/looztra/asdf-conftest)
> feat: provide conftest

- README.md
- plugins/dive
| dive | [looztra/asdf-dive](https://github.com/looztra/asdf-dive) | [![Build Status](https://travis-ci.org/looztra/asdf-dive.svg?branch=master)](https://travis-ci.org/looztra/asdf-dive)
> feat: provide dive

- README.md
- plugins/hadolint
| hadolint | [looztra/asdf-hadolint](https://github.com/looztra/asdf-hadolint) | [![Build Status](https://travis-ci.org/looztra/asdf-hadolint.svg?branch=master)](https://travis-ci.org/looztra/asdf-hadolint)
> feat: provide hadolint

- README.md
- plugins/k9s
| k9s       | [looztra/asdf-k9s](https://github.com/looztra/asdf-k9s) | [![Build Status](https://travis-ci.org/looztra/asdf-k9s.svg?branch=master)](https://travis-ci.org/looztra/asdf-k9s)
> feat: provide k9s

- README.md
- plugins/stern
| stern | [looztra/asdf-stern](https://github.com/looztra/asdf-stern) | [![Build Status](https://travis-ci.org/looztra/asdf-stern.svg?branch=master)](https://travis-ci.org/looztra/asdf-stern)
> feat: provide stern

- README.md
- plugins/velero
| velero | [looztra/asdf-velero](https://github.com/looztra/asdf-velero) | [![Build Status](https://travis-ci.org/looztra/asdf-velero.svg?branch=master)](https://travis-ci.org/looztra/asdf-velero)
> feat: provide velero

- README.md
- plugins/reg
| reg       | [looztra/asdf-reg](https://github.com/looztra/asdf-reg) | [![Build Status](https://travis-ci.org/looztra/asdf-reg.svg?branch=master)](https://travis-ci.org/looztra/asdf-reg)
> feat: provide reg

- README.md
- plugins/terraform-validator
| terraform-validator | [looztra/asdf-terraform-validator](https://github.com/looztra/asdf-terraform-validator) | [![Build Status](https://travis-ci.org/looztra/asdf-terraform-validator.svg?branch=master)](https://travis-ci.org/looztra/asdf-terraform-validator)
> feat: provide terraform-validator

- README.md
- plugins/rbac-lookup
| rbac-lookup       | [looztra/asdf-rbac-lookup](https://github.com/looztra/asdf-rbac-lookup) | [![Build Status](https://travis-ci.org/looztra/asdf-rbac-lookup.svg?branch=master)](https://travis-ci.org/looztra/asdf-rbac-lookup)
> feat: provide rbac-lookup

- README.md
- plugins/osctl
Current build status: ![Build Status](https://travis-ci.org/particledecay/asdf-osctl.svg?branch=master)
> Add Talos osctl command to plugins

- README.md
- plugins/ocaml
Context: https://github.com/vic/asdf-ocaml/issues/15
> Update OCaml plugin repository url to use the new location

- README.md
- plugins/gauche
[Gauche](https://practical-scheme.net/gauche/index.html) is a R7RS scheme implementation by @shirok.
This PR adds asdf plugin which handles Gauche versions to the list.
> Add gauche

- README.md
- plugins/zig
| Zig      | [cheetah/asdf-zig](https://github.com/cheetah/asdf-zig) | [![Build Status](https://travis-ci.org/cheetah/asdf-zig.svg?branch=master)](https://travis-ci.org/cheetah/asdf-zig)
Thank you
> Add Zig plugin

- README.md
- plugins/dhall
| Language | Repository	| CI Status |
|---|---|---|
| [dhall](https://github.com/dhall-lang/dhall-haskell) | [aaaaninja/asdf-dhall](https://github.com/aaaaninja/asdf-dhall) | [![Build Status](https://travis-ci.com/aaaaninja/asdf-dhall.svg?branch=master)](https://travis-ci.com/aaaaninja/asdf-dhall) |
> Add plugin for dhall

- README.md
- plugins/1password
Adds [1password CLI](https://1password.com/downloads/command-line/) version management.
> Add plugin entry

- README.md
- plugins/ccache
**Note**: Decide either merge or close #144 before merging this.
> Add ccache

- README.md
- plugins/binnacle
> Add binnacle

- README.md
- plugins/minio
MinIO is an object storage server compatible with Amazon S3 cloud storage service.
[![Build Status](https://travis-ci.org/aeons/asdf-minio.svg?branch=master)](https://travis-ci.org/aeons/asdf-minio)
> Add minio plugin

- README.md
- plugins/sbcl
> Added Steel Bank Common Lisp (sbcl) 

- README.md
- plugins/elm
Context: https://github.com/asdf-community/asdf-elm/issues/1
> Update elm plugin

- README.md
- plugins/reckoner
[![Build Status](https://github.com/mjhuber/asdf-reckoner/workflows/master/badge.svg)](https://github.com/mjhuber/asdf-reckoner/actions)
> Add reckoner

- README.md
- plugins/rust
Reverts asdf-vm/asdf-plugins#162
> Revert "Update rust plugin"

- README.md
- plugins/sbt
the gabrielelana asdf-sbt repo has gone stale and currently
the `list-all` is broken on master. My fork has this fixed
and happy to take over ownership.
> Move to working sbt plugin repo

- README.md
Hi, I've not found the link of 1password.
> modify 1password Repository on README.md

- README.md
- plugins/kind
> Add support for kind

- README.md
- plugins/neovim
[![Build Status](https://travis-ci.org/richin13/asdf-neovim.svg?branch=master)](https://travis-ci.org/richin13/asdf-neovim)
> Add neovim plugin

- README.md
- plugins/pulumi
Hi, here's a new one that wasn't covered yet 🙂.
> Add Pulumi plugin

- README.md
> Fix typo ("it's" → "its") and comma splice

- test_plugin.sh
Fixing `test_plugin.sh` after I noticed tests were failing for https://github.com/asdf-vm/asdf-plugins/pull/304
> Updating test_plugin.sh

- plugins/ytt
Already done in https://github.com/asdf-vm/asdf-plugins/pull/224/
If you are using github, you might want to use the
`plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions)
No idea though why this isn't working: 
```bash
./test_plugin.sh --file plugins/ytt
Checking plugins/ytt
Expected plugin CI badge SVG to be passing but it was not: https://github.com/k14s/asdf-k14s/workflows/test-all/badge.svg
```
If there is anything else that is relevant to your pull request include that
information here.
Thank you for contributing to asdf-plugins!
> feat: add ytt plugin

- plugins/link
add `plugins/*` file for `link` plugin
```bash
```
> fix: add file for link plugin

- plugins/link
> fix: link plugin config format

- README.md
- plugins/act
- plugins/k6
- plugins/soracom
- plugins/starship
- plugins/terraformer
Description: 
SInce the user name of user "gr1m0h" has been changed, it has also been reflected in asdf-plugins.
- Plugin repo URL:
- https://github.com/gr1m0h/asdf-act
- https://github.com/gr1m0h/asdf-k6
- https://github.com/gr1m0h/asdf-soracom
- https://github.com/gr1m0h/asdf-starship
- https://github.com/gr1m0h/asdf-terraformer
> feat: Update username grimoh -> gr1m0h

- README.md
- plugins/mockolo
Description:
- Tool repo URL: https://github.com/uber/mockolo
- Plugin repo URL: https://github.com/MontakOleg/asdf-mockolo 
> feat: add mockolo asdf-plugin

- README.md
- plugins/scie-pants
Description:
- Tool repo URL: [https://github.com/pantsbuild/scie-pants](https://github.com/pantsbuild/scie-pants)
- Plugin repo URL: [https://github.com/robzr/asdf-scie-pants](https://github.com/robzr/asdf-scie-pants)
> feat: add scie-pants

- README.md
- plugins/dapr
Description:
- Tool repo URL: https://github.com/dapr/dapr
- Plugin repo URL: https://github.com/asdf-community/asdf-dapr-cli
> feat: add dapr

- README.md
- plugins/ollama
Description:
- Tool repo URL: https://github.com/ollama/ollama
- Plugin repo URL: https://github.com/virtualstaticvoid/asdf-ollama
> feat: ollama plugin

- README.md
- plugins/sver
Description:
- Tool repo URL: http://github.com/robzr/sver
- Plugin repo URL: http://github.com/robzr/asdf-sver
> feat: add sver plugin

- README.md
- plugins/uv
Description:
- Tool repo URL: https://github.com/astral-sh/uv
- Plugin repo URL: https://github.com/b1-luettje/asdf-uv
> feat: Add asdf-uv plugin

- README.md
- plugins/daytona
Description:
- Tool repo URL: https://github.com/daytonaio/daytona
- Plugin repo URL: https://github.com/CrouchingMuppet/asdf-daytona
> feat: Added plugin for daytona (https://github.com/daytonaio/daytona)

- README.md
- plugins/typst
[Typst](https://github.com/typst/typst) plugin implementation.
See https://github.com/asdf-vm/asdf-plugins/issues/974
> feat: add typst plugin (#974)

- README.md
- plugins/pkl
Description:
- Tool repo URL: [https://github.com/apple/pkl](https://github.com/apple/pkl)
- Plugin repo URL: [https://github.com/mise-plugins/asdf-pkl](https://github.com/mise-plugins/asdf-pkl)
> feat: add pkl plugin

- README.md
- plugins/sui
Description:
- Tool repo URL: https://github.com/MystenLabs/sui
- Plugin repo URL: https://github.com/placeholder-soft/asdf-sui
> feat: add sui

- README.md
- plugins/helix-editor
Description:
- Tool repo URL: https://github.com/helix-editor/helix
- Plugin repo URL: https://github.com/CSergienko/asdf-helix
- [ X ] Format with `scripts/format.bash`
- [ X ] Test locally with `scripts/test_plugin.bash --file plugins/<your_new_plugin_name>`
- [ X ] Your plugin CI tests are green
> feat: add helix editor

- README.md
- plugins/nerves-toolchain
Description:
- Tool repo URL: https://github.com/nerves-project/toolchains
- Plugin repo URL: https://github.com/nerves-project/asdf-plugin-nerves-toolchain
> feat: add nerves-toolchain plugin

- README.md
- plugins/konstraint
Description:
- Tool repo URL: https://github.com/plexsystems/konstraint
- Plugin repo URL: https://github.com/tapih/asdf-konstraint
> feat: add konstraint plugin

- README.md
- plugins/fastlane
Description:
- Tool repo URL: https://github.com/fastlane/fastlane
- Plugin repo URL: https://github.com/mollyIV/asdf-fastlane
> feat: add fastlane plugin

- README.md
- plugins/rpk
Description:
- Tool repo URL: https://github.com/redpanda-data/redpanda
- Plugin repo URL: https://github.com/jleight/asdf-rpk
> feat: add rpk plugin

- README.md
- plugins/woodpecker-cli
Description: Add woodpecker-cli
- Tool repo URL: https://github.com/woodpecker-ci/woodpecker
- Plugin repo URL: https://github.com/ivanvc/asdf-woodpecker
> feat: add woodpecker-cli

- README.md
- plugins/frankenphp
Description:
- Tool repo URL: https://github.com/dunglas/frankenphp
- Plugin repo URL: https://github.com/theutz/asdf-frankenphp
> feat: add frankenphp

- README.md
- plugins/powerpipe
Description:
- Tool repo URL: https://github.com/turbot/powerpipe
- Plugin repo URL: https://github.com/vmdude/asdf-powerpipe
> feat: add powerpipe

- README.md
- plugins/krelay
Add krelay plugin.
Description:
- Tool repo URL:
- Plugin repo URL: https://github.com/asdf-community/asdf-krelay.git
> feat: add krelay

- README.md
- plugins/sqlc
Description:
- Tool repo URL: https://github.com/sqlc-dev/sqlc
- Plugin repo URL: https://github.com/dylanrayboss/asdf-sqlc
> feat: add sqlc

- README.md
- plugins/falco
Description:
- Tool repo URL: https://github.com/ysugimoto/falco
- Plugin repo URL: https://github.com/ronnnnn/asdf-falco
> feat: asdf-falco

- README.md
- plugins/bingo
Description:
- Tool repo URL: https://github.com/bwplotka/bingo
- Plugin repo URL: https://github.com/isindir/asdf-bingo
> feat: adding plugin for bingo
